# Generated by Django 6.0.3 on 2026-04-28 10:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100, unique=True)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceBreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('resolved', models.BooleanField(default=False)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='geofence.geofence')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='monitoring.livestock')),
            ],
        ),
    ]
