# Generated by Django 6.0.3 on 2026-04-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
